service:
  metadata:
    name: crud-svc
  #protocol: TCP
  port: 80


deploy:
  metadata:
    name: crud-deploy
  name: crud-app
  replicas: 2
  container:
    name: crud-con
    imageRep: senzxita/crud-node-app
    protocol: TCP
    port: 5551

  