apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{ .Release.Name }}-{{ .Values.deploy.metadata.name }}"
  labels: 
    app: {{ .Values.deploy.name }}
spec: 
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}
    spec:
      containers:
      - name: {{ .Values.deploy.container.name }}
        image: "{{ .Values.deploy.container.imageRep }}:{{ .Chart.AppVersion }}"
        #protocol: {{ .Values.deploy.container.protocol }}
        ports:
        - containerPort: {{ .Values.deploy.container.port }}
