apiVersion: v1
kind: Service
metadata: 
  name: "{{ .Release.Name }}-{{ .Values.service.metadata.name }}"
  labels: 
    app: {{ .Values.deploy.name }}
spec: 
  type: LoadBalancer
  selector:
    app: {{ .Values.deploy.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploy.container.port }}
     # nodePort: {{ .Values.service.port }}