name: Node App Docker Image CI
env:
  REPOSITORY_NAME: logicalogbonna

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:

  docker-build:

    runs-on: ubuntu-latest
    env:
      APPLICATION_NAME: node-sample-application
      DOCKER_REPOSITORY: logicalogbonna/node-sample-application

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
    
    - name: Build App
      run: |
        docker build -t ${{env.DOCKER_REPOSITORY}}:${{ github.sha }} .
        docker push ${{env.DOCKER_REPOSITORY}}:${{ github.sha }}
  
  deploy: 
    runs-on: ubuntu-latest
    needs: docker-build

    steps:  
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Clone GitOps repo 
        uses: actions/checkout@v2
        with:
          repository: "ashton-arinze/kubernetes"
          path: kubernetes
          # token: ${{ secrets.my_pat }}
          ref: master

      - name: Change tag and push changes
        run: |
          cd kubernetes
          ls
          yq eval -i ".image.tag = \"${{github.sha}}\"" kubernetes/argo-cd/sample-fullstack-app.yml
          head kubernetes/argo-cd/sample-fullstack-app.yml

          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false  # merge
          git add kubernetes/argo-cd/sample-fullstack-app.yml
          git commit -m "CI - Deployed this ${{github.sha}} version"
          git fetch
          git pull
          git push
    
        
    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: ${{env.REPOSITORY_NAME}}/node-sample-application
    
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}


#/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/2.x*:refs/remotes/origin/2.x* +refs/tags/2.x*:refs/tags/2.x*