name: Node App Docker Image CI
env:
      APPLICATION_NAME: node-sample-application
      DOCKER_REPOSITORY: logicalogbonna/node-sample-application
on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
    
    - name: Build App
      run: |
        docker build -t ${{env.DOCKER_REPOSITORY}}:${{ github.sha }} .
        docker push ${{env.DOCKER_REPOSITORY}}:${{ github.sha }}
  
  deploy: 
    runs-on: ubuntu-latest
    needs: docker-build

    steps:  
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Clone GitOps repo 
        uses: actions/checkout@v2
        with:
          repository: "ashton-arinze/kubernetes"
          path: kubernetes
          token: ${{ secrets.my_pat }}
          ref: master

      - name: Change tag and push changes
        run: |
          cd kubernetes
          ls
          yq eval -i ".spec.template.spec.containers[0].image = \"${{env.DOCKER_REPOSITORY}}:${{ github.sha }}\"" argo-cd/node-app/deployment.yml
          head argo-cd/node-app/deployment.yml

          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false  # merge
          git add argo-cd/node-app/deployment.yml
          git commit -m "CI - Deployed Changes with commit sha ${{github.sha}}"
          git fetch
          git pull
          git push